### ISSUE TITLE
Major issue with CSS linking

### ISSUE THREAD

**Issue by loralighte** [fushra/mdev#2]
![image](https://user-images.githubusercontent.com/62919224/124268660-0c1df800-daf7-11eb-927f-505ae00efb7d.png)
So I was working on the potabi.com website some more as I want to get it done before the Monday meeting for Fivnex. Turns out, there was this MAJOR error.

When linking the CSS file, it is outputting the following link tag:
```html
<link rel="stylesheet" type="text/css" rel="/css/0.css">
```

The correct syntax would be
```html
<link rel="stylesheet" type="text/css" href="./css/0.css">
<!-- Alternative but still functional option -->
<link rel="stylesheet" type="text/css" href="css/0.css">
```

This is a horrible error to have, especially if new users have this happen and don't know why it is happening.

**Comment by trickypr** [comment]
This should be fixed, please update with:
```sh
npm update -g mld
```
